version: "3.9"
services:
    web-reporting:
      build: .
      env_file:
        - .env.local

      ports: 
        - '${PORT}:${PORT}'


    redis:
      image: "redis:alpine"
      ports:
        - '6379:6379'
    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"

