export const WS_POST_COMMAND = 'WS_POST_COMMAND';
export const WS_POST_COMMAND_SUCCEEDED = 'WS_POST_COMMAND_SUCCEEDED';
export const WS_POST_COMMAND_FAILED = 'WS_POST_COMMAND_FAILED';

export const SERVER_DATA_DELETE = 'SERVER_DATA_DELETE';
export const LOG_DATA_DELETE = 'LOG_DATA_DELETE';
export const LOG_UPDATE = 'LOG_UPDATE';
export const DEVICES_CONTEXT_UPDATE = 'DEVICES_CONTEXT_UPDATE';
export const TARGET_UPDATE = 'TARGET_UPDATE';
export const TARGET_HIT = 'TARGET_HIT';
export const DISPLAY_UPDATE = 'DISPLAY_UPDATE';

/**
 * Sender: UI-CLIENT
 */
export const REQUEST_SERVER_STATUS = 'REQUEST_SERVER_STATUS';
export const REQUEST_SERVER_STATUS_SUCCEEDED =
  'REQUEST_SERVER_STATUS_SUCCEEDED';
export const REQUEST_SERVER_LOG = 'REQUEST_SERVER_LOG';
export const REQUEST_SERVER_LOG_SUCCEEDED = 'REQUEST_SERVER_LOG_SUCCEEDED';
export const REQUEST_REGISTERED_DEVICES = 'REQUEST_REGISTERED_DEVICES';
export const REQUEST_REGISTERED_DEVICES_SUCCEEDED =
  'REQUEST_REGISTERED_DEVICES_SUCCEEDED';
export const SET_STATE = 'SET_STATE';
export const SET_STATE_SUCCEEDED = 'SET_STATE_SUCCEEDED';
export const SET_STATE_FAILED = 'SET_STATE_FAILED';
export const START_GAME = 'START_GAME';
export const START_GAME_SUCCEEDED = 'START_GAME_SUCCEEDED';
export const START_GAME_FAILED = 'START_GAME_FAILED';
export const END_GAME = 'END_GAME';
export const END_GAME_SUCCEEDED = 'END_GAME_SUCCEEDED';
export const END_GAME_FAILED = 'END_GAME_FAILED';
